"""asasas

Revision ID: 2f38236847f7
Revises: 2553081ed8e2
Create Date: 2023-08-25 22:16:44.291886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f38236847f7'
down_revision = '2553081ed8e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('diagnostics', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('diagnostics', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('questions', 'question_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('diagnostics', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('diagnostics', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('customers', 'status')
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
